apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: broker.amq.io
      version: v1beta1
      kind: ActiveMQArtemis
      name: default
    patch: |-
      - op: add
        path: /spec/acceptors/-
        value:
          name: ssl
          expose: true
          port: 61617
          protocols: all

          multicastPrefix: jms.topic.
          anycastPrefix: jms.queue.

          sslEnabled: true
          needClientAuth: false
          sslSecret: acceptor-ssl-keystore
          trustSecret: acceptor-ssl-truststore
